version: '3.5'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile-EventsAPI
    volumes:
      - ./eventsAPI:/eventsAPI
    env_file:
      - ./.env
    ports:
      - 10000:10000
    depends_on:
      - rabbit


  rabbit:
    image: rabbitmq:3.6-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
    - rabbitmq_data:/usr/share/rabbitmq_data

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile-scheduler
    env_file:
      - ./.env
    ports:
      - 4000:4000
    depends_on:
      - postgres

  postgres:
    image: postgres:13-alpine
    env_file:
      ./.env
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  rabbitmq_data:
  pg_data:
  redis_data: