version: '3.5'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile-EventsAPI
    volumes:
      - ./eventsAPI:/eventsAPI
    env_file:
      - ./.env
    ports:
      - 10000:10000
    depends_on:
      - rabbit


  rabbit:
    image: rabbitmq:3.6-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
    - rabbitmq_data:/usr/share/rabbitmq_data

  auth:
    build:
      context: .
      dockerfile: Dockerfile-auth
    volumes:
      - ./auth:/auth
    env_file:
      - ./.env
    ports:
      - 8001:8001
    depends_on:
      - postgres
      - redis

  administration:
    build:
      context: .
      dockerfile: Dockerfile-administration_events
    volumes:
      - static_volume:/Administration_event_service/staticfiles
    env_file:
      - ./.env
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:13-alpine
    env_file:
      ./.env
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  redis:
    image: redis
    volumes:
      - redis_data:/data

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27019:27017
    expose:
      - "27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro

  ugc:
    build:
      context: .
      dockerfile: Dockerfile-ugc
    volumes:
      - ./ugc:/ugc
    env_file:
      - ./.env
    ports:
      - 7777:7777
    depends_on:
      - mongo

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile-scheduler
    env_file:
      - ./.env
    ports:
      - 4000:4000
    depends_on:
      - scheduler-postgres

  scheduler-postgres:
    image: postgres:13-alpine
    env_file:
      ./.env
    volumes:
      - shceduler_pg_data:/var/lib/postgresql/data

  nginx:
    container_name: ymp_nginx
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - static_volume:/Administration_event_service/staticfiles
    ports:
      - 8000:80
    depends_on:
      - administration
    restart: always

volumes:
  shceduler_pg_data:
  rabbitmq_data:
  pg_data:
  redis_data:
  static_volume: