FROM python:3.9-slim-buster

WORKDIR /scheduler

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN pip install --upgrade pip

COPY ./requirements/scheduler.txt ./
RUN pip install -r ./scheduler.txt

COPY ./scheduler /scheduler

CMD python waiter.py && gunicorn main:app -b 0.0.0.0:4000 --reload
