FROM python:3.9-slim-buster

WORKDIR /usr/src/app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN pip install --upgrade pip

COPY ./django_admin/requirements/ ./requirements

RUN pip install -r ./requirements/dev.txt

# предполагаем, что у нас dev окружение, по-этому --reload
CMD gunicorn config.wsgi:application --bind 0.0.0.0:8000 -p 8000 --reload
